- name: Update and Upgrade Packages
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: Update repositories
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: safe
        autoclean: yes
        autoremove: yes

    - name: Clear apt cache
      apt:
        autoclean: yes

    - name: Remove unused packages
      apt:
        name: "*"
        state: autoremove

    - name: Clear apt cache (again)
      apt:
        autoclean: yes

    - name: Clear apt cache (final cleanup)
      shell: sudo apt-get clean

    - name: Clear temporary files
      shell: rm -rf /tmp/*
