- name: Update and Upgrade Packages
  hosts: all
  tasks:
    - name: Update all packages
      ansible.builtin.shell:
        command: sudo apt update

    - name: Upgrade all packages
      ansible.builtin.shell:
        command: sudo apt upgrade -y
