- name: Update and Upgrade Packages
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: Update repositories
      apt:
        update_cache: yes
      become: true

    - name: Upgrade packages
      apt:
        upgrade: safe
        autoclean: yes
        autoremove: yes
      become: true
