- name: Display System Usage and Capacities
  hosts: all
  tasks:
    - name: Display disk usage
      command: sudo df -h
      register: disk_usage_output

    - name: Display memory usage
      command: sudo free -h
      register: memory_usage_output

    - name: Display system load
      command: sudo uptime
      register: system_load_output

    - name: Display disk capacities
      command: sudo fdisk -l
      register: disk_capacities_output

    - name: Display system usage and capacities
      debug:
        var: item.stdout_lines
      loop:
        - "{{ disk_usage_output }}"
        - "{{ memory_usage_output }}"
        - "{{ system_load_output }}"
        - "{{ disk_capacities_output }}"
