- name: Test Sudo Privileges
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Test sudo privileges
      command: echo "Testing sudo privileges" >> /tmp/testfile
      register: result

    - name: Display command output
      debug:
        var: result.stdout_lines

    - name: Remove test file
      command: rm /tmp/testfile
      register: cleanup_result
      ignore_errors: true

    - name: Display cleanup output
      debug:
        var: cleanup_result.stdout_lines
